### ISSUE TITLE
Hello, where is the example in the video that I can't find

### ISSUE THREAD

**Issue by gsm958708323** [nilpunch/unity-prediction-rollback#1]
![image](https://github.com/nilpunch/unity-prediction-rollback/assets/29498846/05cf4542-8ffa-467a-a4ed-451f70d510b6)

**Comment by nilpunch** [comment]
Hello,

In the project, I used the same SampleScene to test all the different functionality. Therefore, there will not be exactly the same scene that you are looking for.

SampleScene still uses command prediction. You can try this by holding down the P key. Basically, when pressed, this key simply disables CharacterController.

**Comment by gsm958708323** [comment]
Okay, thank you
